DROP DATABASE IF EXISTS reportservice;
DROP USER IF EXISTS `reportservice_user`@`%`;
CREATE DATABASE IF NOT EXISTS reportservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `reportservice_user`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `reportservice`.* TO `reportservice_user`@`%`;
FLUSH PRIVILEGES;